eureka:
  instance:
    hostname: ${EUREKA_CLIENT_HOST}
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL}/eureka/
    fetch-registry: true

spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        # Comments service
        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/api/v1/comment/**, /comment/**
          filters:
            - RewritePath=/comment/(?<path>.*), /$\{path}
        # Reports service
        - id: reports-service
          uri: lb://REPORTS-SERVICE
          predicates:
            - Path=/api/v1/reports/**, /reports/**
          filters:
            - RewritePath=/reports/(?<path>.*), /$\{path}
        # Danger zone service
        - id: danger-zone-service
          uri: lb://DANGER-ZONE-SERVICE
          predicates:
            - Path=/api/v1/danger-zone/**, /danger-zone/**
          filters:
            - RewritePath=/danger-zone/(?<path>.*), /$\{path}
        # Eureka server
        - id: eureka-server-web
          uri: ${eureka.client.serviceUrl.defaultZone}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        # Eureka server static
        - id: eureka-server-static
          uri: ${eureka.client.serviceUrl.defaultZone}
          predicates:
            - Path=/eureka/**
        # Openapi
        - id: openapi
          uri: http://localhost:8080/
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG